# Generated by Django 3.2.4 on 2021-06-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Servicio al Cliente', 'Servicio al Cliente'), ('Indefinido', 'Indefinido')], default='Tecnico', max_length=50),
        ),
    ]
