# Generated by Django 3.2.4 on 2021-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Tecnico', 'Tecnico'), ('Servicio al Cliente', 'Servicio al Cliente')], default='Indefinido', max_length=50),
        ),
    ]
