
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
tasks:
  - name: Python Server
    command: >
      pipenv --rm &&
      echo 'Y'|pipenv shell &&
      pipenv install &&
      python manage.py runserver

  - name: NPM Server
    command: >
        cd frontend &&
        sleep 3 &&
        npm run serve &&
  - name: Misc Server
    command: >
        sleep 3
        git status
ports:
  - port: 8000-8081
    visibility: public
    onOpen: ignore


vscode:
  extensions:
    - zhuangtongfa.material-theme
    - formulahendry.auto-close-tag
    - steoates.autoimport
    - hookyqr.beautify
    - coenraads.bracket-pair-colorizer-2
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - robbowen.synthwave-vscode
    - octref.vetur
    - ms-python.python
    - ms-toolsai.jupyter
    - aaron-bond.better-comments
