
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000-8080
    visibility: public
    onOpen: ignore
tasks:
  - name: Python Server
    command: >
      sleep 3
      pipenv --rm
      sleep 3
      echo 'y'|pipenv shell
      sleep 3
      pipenv install
      sleep 3
      python manage.py runserver

  - name: NPM Server
    command: >
      sleep 3
      cd frontend
      sleep 3
      npm run serve
  - name: Misc Server
    command: >
      sleep 3
      git status


vscode:
  extensions:
    - zhuangtongfa.material-theme
    - formulahendry.auto-close-tag
    - steoates.autoimport
    - hookyqr.beautify
    - coenraads.bracket-pair-colorizer-2
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - robbowen.synthwave-vscode
    - octref.vetur
    - ms-python.python
    - ms-toolsai.jupyter
    - aaron-bond.better-comments
