# Generated by Django 3.2.4 on 2021-06-19 00:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=50)),
                ('client_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
                ('service_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_type', models.CharField(choices=[('Inicial', 'Inicial'), ('Actualizacion', 'Actualizacion'), ('Final', 'Final')], default=None, max_length=15)),
                ('noc_ticket', models.CharField(default=None, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('third_party_ticket', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('date_of_outage', models.DateField(default=datetime.date.today, verbose_name='Fecha de Evento')),
                ('time_of_outage', models.TimeField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('municipalities', models.CharField(max_length=200)),
                ('causes', models.ManyToManyField(blank=True, to='report_builder.Cause')),
                ('clients', models.ManyToManyField(blank=True, to='report_builder.Clients')),
                ('outage_type', models.ManyToManyField(blank=True, to='report_builder.OutageType')),
                ('services', models.ManyToManyField(blank=True, to='report_builder.Services')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report_builder.report')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
