# Generated by Django 3.2.3 on 2021-05-24 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_type', models.CharField(choices=[('Inicial', 'Inicial'), ('Actualizacion', 'Actualizacion'), ('Final', 'Final')], default=None, max_length=15)),
                ('noc_ticket', models.CharField(default=None, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('third_party_ticket', models.CharField(blank=True, max_length=15, unique=True)),
                ('date_of_outage', models.DateField(default=datetime.date.today, verbose_name='Fecha de Evento')),
                ('time_of_outage', models.TimeField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('municipalities', models.CharField(max_length=200)),
                ('cause', models.ManyToManyField(blank=True, to='report_builder.Cause')),
                ('client_amount', models.ManyToManyField(blank=True, to='report_builder.ClientAmount')),
                ('clients', models.ManyToManyField(blank=True, to='report_builder.Clients')),
                ('outage_type', models.ManyToManyField(blank=True, to='report_builder.OutageType')),
                ('service_amount', models.ManyToManyField(blank=True, to='report_builder.ServiceAmount')),
                ('services', models.ManyToManyField(blank=True, to='report_builder.Services')),
            ],
        ),
    ]
