# Generated by Django 3.2.5 on 2022-02-18 03:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='OutageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_type', models.CharField(choices=[('Inicial', 'Inicial'), ('Actualización', 'Actualización'), ('Finalizado', 'Finalizado')], default=None, max_length=15)),
                ('noc_ticket', models.CharField(default=None, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('third_party_ticket', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('date_of_outage', models.DateField(default=datetime.date.today, verbose_name='Fecha de Evento')),
                ('time_of_outage', models.TimeField(blank=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('municipalities', models.CharField(max_length=200)),
                ('outage_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('causes', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('equipment', models.JSONField(default=dict)),
                ('clients', models.JSONField(default=dict)),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=255)),
                ('published', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report_builder.report')),
            ],
            options={
                'ordering': ('published',),
            },
        ),
    ]
