# Generated by Django 3.2.4 on 2021-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='causes',
            field=models.ManyToManyField(blank=True, related_name='causes_fiels', to='report_builder.Cause'),
        ),
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients_field', to='report_builder.Clients'),
        ),
        migrations.AlterField(
            model_name='report',
            name='outage_type',
            field=models.ManyToManyField(blank=True, related_name='outage_type_field', to='report_builder.OutageType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services_field', to='report_builder.Services'),
        ),
    ]
