# Generated by Django 3.2.3 on 2021-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='cause',
            new_name='causes',
        ),
    ]
