# Generated by Django 3.2.4 on 2021-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_auto_20210702_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='causes',
            field=models.ManyToManyField(blank=True, related_name='causes_field', to='report_builder.Cause'),
        ),
    ]
