# Generated by Django 3.2.5 on 2022-02-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
