# Generated by Django 3.2.3 on 2021-05-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0002_rename_cause_report_causes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='third_party_ticket',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
