# Generated by Django 3.2.5 on 2021-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0003_auto_20210920_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='causes',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_amount',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='outage_type',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_amount',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='services',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
