# Generated by Django 3.2.4 on 2021-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0003_alter_report_causes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='causes',
            field=models.ManyToManyField(blank=True, to='report_builder.Cause'),
        ),
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.ManyToManyField(blank=True, to='report_builder.Clients'),
        ),
        migrations.AlterField(
            model_name='report',
            name='outage_type',
            field=models.ManyToManyField(blank=True, to='report_builder.OutageType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='services',
            field=models.ManyToManyField(blank=True, to='report_builder.Services'),
        ),
    ]
