# Generated by Django 3.2.5 on 2021-09-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0005_auto_20210922_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='json_client',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='json_service',
            field=models.JSONField(default=dict),
        ),
    ]
