# Generated by Django 3.2.5 on 2021-09-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0006_auto_20210922_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='client_amount',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='clients',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='service_amount',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='services',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
