# Generated by Django 3.2.5 on 2021-09-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0007_auto_20210922_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='client_amount',
        ),
        migrations.RemoveField(
            model_name='report',
            name='json_client',
        ),
        migrations.RemoveField(
            model_name='report',
            name='json_service',
        ),
        migrations.RemoveField(
            model_name='report',
            name='service_amount',
        ),
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='services',
            field=models.JSONField(default=dict),
        ),
    ]
